name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
    - run: docker build --pull --cache-from darkmattercoder/qt-build:builder-5.12.4 --build-arg QT_VERSION_MAJOR=5 --build-arg QT_VERSION_MINOR=12 --build-arg QT_VERSION_PATCH=4 --build-arg QT_DOWNLOAD_BRANCH=official_releases --build-arg QT_TARBALL_NAMING_SCHEME=everywhere --build-arg CI_BUILD=2 --build-arg CORE_COUNT=2 --target=builder -t darkmattercoder/qt-build:builder-5.12.4 .
